### PR TITLE
Some suggestions, this could be improved still.

### PR DESCRIPTION
**Pull request by arran4**
Hey, this is a pull request INTO your pull request. 

There still might be some good work which could be done here.

It also occurred to me that if you were to put a "read counter" in:
https://github.com/arran4/golang-ical/blob/84e95bcb9f6760d1b288e655977a3fc5e2ae6fa9/calendar.go#L523-L533
https://github.com/ManoloTonto1/golang-ical/blob/84e95bcb9f6760d1b288e655977a3fc5e2ae6fa9/calendar.go#L523-L533

And put it in the function here;
https://github.com/arran4/golang-ical/blob/84e95bcb9f6760d1b288e655977a3fc5e2ae6fa9/calendar.go#L535-L590
https://github.com/ManoloTonto1/golang-ical/blob/84e95bcb9f6760d1b288e655977a3fc5e2ae6fa9/calendar.go#L535-L590

You could a line offset and with some smart refactoring a character offset inserted in the errors raised in:
https://github.com/arran4/golang-ical/blob/84e95bcb9f6760d1b288e655977a3fc5e2ae6fa9/calendar.go#L438-L521
https://github.com/ManoloTonto1/golang-ical/blob/84e95bcb9f6760d1b288e655977a3fc5e2ae6fa9/calendar.go#L438-L521

A bit like any other parser. 

Anyway. Please review this, then make some improvements if you can find any and then we can merge upstream into master once done.

### CODE REVIEW

**Comment by arran4** [comment]
@ManoloTonto1 This is my "reverse" pull request, a PR into your PR to fix some changes. I haven't reviewed if they are still relevant just fixed the conflicts so you can. This PR goes into https://github.com/arran4/golang-ical/pull/73 which has stagnated. 

I have replaced a couple of PRs with my own which tries to resolve issues with them and I will wait a short while before merging them myself (feel free to review them if you like.) I can take over yours ( https://github.com/arran4/golang-ical/pull/73 ) too and replace it with my own (I will be keeping your commits so in essence I will be duplicating this pr https://github.com/ManoloTonto1/golang-ical/pull/1 into mine. )

**Comment by arran4** [comment]
Actually rebased it with master too. This should improve things. You will have to enable actions on your fork to see if the tests works before accepting the merge *into your pull request* sorry these things tend to be a bit confusing. I wish github supported "suggest a change" like gitlab has

**Comment by arran4** [comment]
@ManoloTonto1 Fixed the failing test b/c of not picking up on the error wrapping of EOF. There are potentially some other of these issues around too.

**Comment by arran4** [comment]
Did a quick spot check. But there could be more issues here too. I'm not 100% on the format strings, but they will work.

**Comment by ManoloTonto1** [comment]
@arran4 shall we merge it? 
Did a quick spot check also, looks good. Thanks for the patience, I haven't had enough time to sit down and fix more things.

**Comment by arran4** [comment]
THis is a PR into your PR, so it's up to you. I suggest yes. But I can go around you and just merge it my branch into the "origin" repo. 

I recommend that you merge it into yours for process sake. So feel free to request changes into your pr. :P

**Comment by arran4** [comment]
But thanks. Happy to wait for you.

**Comment by ManoloTonto1** [comment]
@arran4 Merged 🚀

**Comment by arran4** [comment]
Alright, looks like some new conflicts have occurred. I will see where this leaves us.

**Pull request merged**
